#TODO: Da rivedere
scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
  - job_name: 'mongo'
    static_configs:
      - targets: ['mongo:27017']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
