global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "game-catalog"
    static_configs:
      - targets: ["game-catalog:3000"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:3000"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:3000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: [ 'cadvisor:8080' ]
